### ISSUE TITLE
Error when trying to use the REST library on SBT REPL

### ISSUE THREAD

**Issue by mrueegg** [codacy/bitbucket-scala-client#5]
Hi,

I just wanted to try your Bitbucket REST lib (which looks awesome by the way). When I execute a request inside of a SBT REPL, I get the following error:

```
scala> val client = new BitbucketClient(key="MY_KEY", secretKey="MY_SECRET_KEY", token="MY_TOKEN", secretToken = "MY_SECRET_TOKEN")
scala> val repos = new RepositoryServices(client)
scala> repos.getRepositories("my_user")

0:33:00.517 [run-main-0] ERROR com.ning.http.client.AsyncHttpClient - Unable to instantiate provider com.ning.http.client.providers.netty.NettyAsyncHttpProvider.  Trying other providers.
20:33:00.520 [run-main-0] ERROR com.ning.http.client.AsyncHttpClient - java.util.concurrent.RejectedExecutionException: Task org.jboss.netty.util.internal.DeadLockProofWorker$1@1300de50 rejected from java.util.concurrent.ThreadPoolExecutor@44c4148e[Running, pool size = 15, active threads = 15, queued tasks = 0, completed tasks = 0]
java.util.concurrent.RejectedExecutionException: Task org.jboss.netty.util.internal.DeadLockProofWorker$1@1300de50 rejected from java.util.concurrent.ThreadPoolExecutor@44c4148e[Running, pool size = 15, active threads = 15, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[na:1.8.0_45]
	at org.jboss.netty.util.internal.DeadLockProofWorker.start(DeadLockProofWorker.java:38) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:368) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.<init>(AbstractNioSelector.java:100) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:52) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:45) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:28) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.newWorker(AbstractNioWorkerPool.java:142) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:80) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:151) ~[netty-3.9.8.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:133) ~[netty-3.9.8.Final.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.<init>(NettyAsyncHttpProvider.java:263) ~[async-http-client-1.8.15.jar:na]
	at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
	at com.ning.http.client.AsyncHttpClient.loadDefaultProvider(AsyncHttpClient.java:554) [async-http-client-1.8.15.jar:na]
	at com.ning.http.client.AsyncHttpClient.<init>(AsyncHttpClient.java:187) [async-http-client-1.8.15.jar:na]
	at play.api.libs.ws.ning.NingWSClient.<init>(NingWS.scala:38) [play-ws_2.10-2.3.9.jar:2.3.9]
	at com.codacy.client.bitbucket.client.BitbucketClient.withClient(BitbucketClient.scala:153) [classes/:na]
	at com.codacy.client.bitbucket.client.BitbucketClient.withClientEither(BitbucketClient.scala:127) [classes/:na]
	at com.codacy.client.bitbucket.client.BitbucketClient.get(BitbucketClient.scala:98) [classes/:na]
	at com.codacy.client.bitbucket.client.BitbucketClient.execute(BitbucketClient.scala:28) [classes/:na]
	at com.codacy.client.bitbucket.service.RepositoryServices.getRepositories(RepositoryServices.scala:14) [classes/:na]
	at $line20.$read$$iw$$iw$.<init>(<console>:12) [na:na]
	at $line20.$read$$iw$$iw$.<clinit>(<console>) [na:na]
	at $line20.$eval$.<init>(<console>:7) [na:na]
	at $line20.$eval$.<clinit>(<console>) [na:na]
	at $line20.$eval.$print(<console>) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837) [scala-compiler-2.10.5.jar:na]
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904) [scala-compiler-2.10.5.jar:na]
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62) [compiler-interface.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101) [compile-0.13.8.jar:0.13.8]
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76) [compile-0.13.8.jar:0.13.8]
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22) [actions-0.13.8.jar:0.13.8]
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23) [actions-0.13.8.jar:0.13.8]
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23) [actions-0.13.8.jar:0.13.8]
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23) [actions-0.13.8.jar:0.13.8]
	at sbt.Logger$$anon$4.apply(Logger.scala:85) [logging-0.13.8.jar:0.13.8]
	at sbt.TrapExit$App.run(TrapExit.scala:248) [run-0.13.8.jar:0.13.8]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
res11: com.codacy.client.bitbucket.client.RequestResponse[Seq[com.codacy.client.bitbucket.SimpleRepository]] =
RequestResponse(None,
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:161)
com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:124)
com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:499)
play.api.libs.ws.ning.NingWSClient.executeRequest(NingW.
```

Do you have any idea what the problem is here?

Another question: ``BitbucketClient`` demands four parameters. Shouldn't it be enough to just specify the OAuth token and the secret token? Is there a reason why it also needs ``key`` and ``secretKey``?When I execute requests to Bitbucket from cURL e.g., I only have to use these two:

```
curl "https://bitbucketories/user/repo?oauth_token_secret=XYZ&oauth_token=XYZ"
```

Thanks,
Michael

**Comment by rtfpessoa** [comment]
@mrueegg this library still uses the OAuth1 from bitbucket and it requires previous retrieval of the token for the user.
You need to do the first part of the OAuth1 where you use the app token to get the other 2.
I think bitbucket updated to OAuth2 but still not sure, need to check.

**Comment by rtfpessoa** [comment]
@mrueegg I just tested and I works normally here.

Since it seems to be related to the threadpool I changed.
I tried to start with Int.MaxValue threads, reducing thread await, but could not replicate the issue.

Can you try to remove the line 152 from `BitbucketClient`: 
```scala
.setExecutorService(new ThreadPoolExecutor(5, 15, 30L, TimeUnit.SECONDS, new SynchronousQueue[Runnable]))
``` 

and see if it still happens with the default pool?

**Comment by pedrorijo91** [comment]
Closing as not getting an answer

**Comment by rtfpessoa** [comment]
Just leaving this here for future information:
http://examples.javacodegeeks.com/core-java/util/concurrent/rejectedexecutionexception/java-util-concurrent-rejectedexecutionexception-how-to-solve-rejectedexecutionexception/
